### ISSUE TITLE
关于NEMu数据集的使用

### ISSUE THREAD

**Issue by ZouChuang711** [ShipingGe/MMER#1]
您好！很高兴接触到您的项目。想请问一下有没有NEMu数据集的文件可以提供下载？需要对数据集包进行什么样的处理？

**Comment by ShipingGe** [comment]
You can find it here: https://github.com/MANLP-suda/Data-set

**Comment by ShipingGe** [comment]
You can find it here: https://github.com/MANLP-suda/Data-set

**Comment by dlutor** [comment]
你好，连接中NEMu是处理前的，能分享处理后的数据吗？For NEMu, the 300-D lyric and comment features are extracted using GloVe model, the 74-D audio features are extracted using Librosa for MFCCs, and the 2048-D image features are extracted using ResNet model。

**Comment by ZouChuang711** [comment]
已收到，谢谢

**Comment by ZouChuang711** [comment]
已收到，谢谢

**Comment by ansucatherine** [comment]
您好，请问可以求一下处理后的数据集吗？

**Comment by ZouChuang711** [comment]
已收到，谢谢
