### ISSUE TITLE
关于loss.backward(retain_graph=true)显示cuda memory error的问题

### ISSUE THREAD

**Issue by Estampie00** [ShipingGe/MMER#2]
您好，我在运行代码到loss.backward(retain_graph=true)的时候，发现cuda memory error的问题，查找之后发现应该是计算图一直没有得到释放导致显存报错，就算将batch_size设置的很小也没有效果。在硬件设备有限的情况下，请问是否能将代码中的loss1.backward(retain_graph=true)和loss2.backward(retain_graph=true)改为total_loss = loss1 + loss2, total_loss.backward？这样虽然不会再报cuda memory error，但是我不知道这和您精巧设置的训练结构是否是等价的。期待您的回答！
<img width="749" alt="微信图片_20240409205220" src="https://github.com/ShipingGe/MMER/assets/76503793/f9e7f328-2c98-4473-80e1-462ebe647a14">

**Comment by ShipingGe** [comment]
从梯度的角度来说两者是一致的，但是可能会因为dropout或者layer norm等操作导致两者结果不一致。

**Comment by ShipingGe** [comment]
从梯度的角度来说两者是一致的，但是可能会因为dropout或者layer norm等操作导致两者结果不一致。另外你可以尝试使用FP16训练的方式，可以缓解显存不足的问题。
